# Generated by Django 4.1.7 on 2023-04-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0004_alter_lfgroups_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfgroups',
            name='date_add',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lfgroups',
            name='date_edit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lfgroups',
            name='day_limit_current',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lfgroups',
            name='hour_limit_current',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lfgroups',
            name='moby',
            field=models.SmallIntegerField(null=True),
        ),
    ]
