# Generated by Django 4.1.7 on 2023-04-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0005_alter_lfgroups_date_add_alter_lfgroups_date_edit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lfgroups',
            options={'managed': False},
        ),
    ]
