# Generated by Django 4.1.7 on 2023-04-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabel', '0006_alter_lfgroups_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lfgroups',
            options={'managed': True},
        ),
    ]
